# -*- coding: utf-8 -*-

# make 
# train_formal 
# train_mix 
# test_mix 
# dev_mix 

"""make_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OJRTmPpwBEcSDGiOqakg6eH0wnqx7S1f
"""

"""# Generate dataset 0423

train_formal (1044897, 3)

train_mix (1044897, 3)

test_mix (130612, 3)

dev_mix (130612, 3)
"""


import pandas as pd
data = pd.read_csv("/content/gdrive/My Drive/Final Project/4995 DL/final/files/train.csv",encoding="utf-8", sep = ",", error_bad_lines=False)
data = data[0:int(data.shape[0]*0.1)]
print(data.shape)
data.head()

train_formal = pd.read_csv('/content/gdrive/My Drive/Final Project/4995 DL/final/files/train_formal.txt', sep="\t",encoding="utf-8",error_bad_lines=False, index_col=False)
train_formal.columns = ["formal_question", "a", "b"]
print(train_formal.shape)
train_formal.head()

train_mix = data[0:int(data.shape[0]*0.8)]
save = pd.DataFrame(train_mix) 
columnsTitles=["qid", "question_text","target"]
save=save.reindex(columns=columnsTitles)
save.to_csv('/content/gdrive/My Drive/Final Project/4995 DL/final/files/train_mix.csv',index=False,header=False, sep='\t')
print(save.shape)
save.head()

test_mix = data[int(data.shape[0]*0.8):int(data.shape[0]*0.8)+int(data.shape[0]*0.1)]
save = pd.DataFrame(test_mix) 
columnsTitles=["qid", "question_text","target"]
save=save.reindex(columns=columnsTitles)
save.to_csv('/content/gdrive/My Drive/Final Project/4995 DL/final/files/test_mix.csv',index=False,header=False, sep='\t')
print(save.shape)
save.head()

dev_mix = data[int(int(data.shape[0]*0.8)+int(data.shape[0]*0.1)):int((data.shape[0]*0.8)+int(data.shape[0]*0.1)+int(data.shape[0]*0.1))]
save = pd.DataFrame(dev_mix) 
columnsTitles=["qid", "question_text","target"]
save=save.reindex(columns=columnsTitles)
save.to_csv('/content/gdrive/My Drive/Final Project/4995 DL/final/files/dev_mix.csv',index=False,header=False, sep='\t')
print(save.shape)
save.head()

data_formal = pd.read_csv('/content/gdrive/My Drive/Final Project/4995 DL/final/files/train_formal.txt', sep="\t",encoding="utf-8",error_bad_lines=False, index_col=False)
data_formal.columns = ["formal_question", "a", "b"]
print(data_formal.shape)
data_formal.head()

train_formal = data_formal[0:int(data.shape[0]*0.8)]
save = pd.DataFrame(train_formal) 
#columnsTitles=["qid", "question_text","target"]
#save=save.reindex(columns=columnsTitles)
save.to_csv('/content/gdrive/My Drive/Final Project/4995 DL/final/files/train_formal.csv',index=False,header=False, sep='\t')
print(save.shape)
save.head()

